### ISSUE TITLE
Core does not limit number of features returned to the value specified with limit

### ISSUE THREAD

**Issue by tazle** [vaisala-oss/sofp-core#2]
E.g. http://10.200.200.2:3000/sofp/collections/testlab/items?limit=10 for Vaisala test server returns 19 features because Vaisala backend doesn't yet know anything about pagination.

Should core limit the number of features returned?

**Comment by sampov2** [comment]
In the current design, the backend needs to take care of page sizes, see https://github.com/vaisala-oss/sofp-example-backend/blob/master/src/index.ts#L69

Once it deems that the page if complete, a null value is pushed to the returned FeatureStream. The page is complete once the limit number of features is reached or the backend decides to return a non-complete page which is accepted by WFS 3.0. Note that the backend must keep track of not how many features it has pushed to the FeatureStream but the count accepted by the FeatureStream (FeatureStream.push returns true when accepted).
