### ISSUE TITLE
Invalid Points

### ISSUE THREAD

**Issue by bosborn** [vaisala-oss/sofp-core#5]
Was testing against your demo server and noticed some invalid geometry points.

http://beta.fmi.fi/data/3/wfs/sofp/collections/opendata_1h/items?time=20190519T140000/20190619T140000&bbox=20.0,60.0,22.0,62.0&limit=15&f=json

Produces points like:

```
"geometry": {
    "type": "Point",
    "coordinates": [
        "[21.69828 20.74698 21.02681 21.30273 21.78320 21.37592 21.51533 20.29765]",
        "[60.1116 60.2582 60.7222 61.1447 61.4789 61.6304 61.1366 60.1158]"
    ]
}
```

**Comment by sampov2** [comment]
Thanks for the report. This issue actually belongs to the project fmidev/smartmet-sofp-backend, I'll copy it over there. Thanks again!
